-d D:\Documents\University of Bath\Education\Year 1\Semester 2\EE10169-Digital Electronics\Coursework\Trial_1\impl\gwsynthesis\Trial_1.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Documents\University of Bath\Education\Year 1\Semester 2\EE10169-Digital Electronics\Coursework\Trial_1\src\Trial_1.cst
-cfg D:\Documents\University of Bath\Education\Year 1\Semester 2\EE10169-Digital Electronics\Coursework\Trial_1\impl\pnr\device.cfg
-sdc D:\Documents\University of Bath\Education\Year 1\Semester 2\EE10169-Digital Electronics\Coursework\Trial_1\src\Trial_1.sdc
-bit
-tr
-ph
-timing
-cst_error
